// <auto-generated />
using System;
using HotelRecord.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HotelRecord.Repository.Migrations
{
    [DbContext(typeof(HotelRecordDbContext))]
    [Migration("20200729160852_ICollection")]
    partial class ICollection
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HotelRecord.Repository.Moduls.Hotel", b =>
                {
                    b.Property<int>("HotelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("HotelChainId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(80)");

                    b.Property<int>("NumberOfEmployees")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfRooms")
                        .HasColumnType("int");

                    b.Property<DateTime>("OpeningYear")
                        .HasColumnType("datetime2");

                    b.HasKey("HotelId");

                    b.HasIndex("HotelChainId");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("HotelRecord.Repository.Moduls.HotelChain", b =>
                {
                    b.Property<int>("HotelChainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("varchar(75)");

                    b.Property<DateTime>("YearOfEstablishment")
                        .HasColumnType("datetime2");

                    b.HasKey("HotelChainId");

                    b.ToTable("HotelChains");
                });

            modelBuilder.Entity("HotelRecord.Repository.Moduls.Hotel", b =>
                {
                    b.HasOne("HotelRecord.Repository.Moduls.HotelChain", "HotelChains")
                        .WithMany("Hotels")
                        .HasForeignKey("HotelChainId");
                });
#pragma warning restore 612, 618
        }
    }
}
